name: Deploy OSB Service

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download OSB JAR from GitHub Packages
        shell: cmd
        run: mvn dependency:get -Dartifact=com.example:osb-service:1.0.0 -DremoteRepositories=github::default::https://maven.pkg.github.com/ShashankDambal/osb-service-repo

      - name: Find and Move OSB JAR
        shell: pwsh
        run: |
          $jarFile = Get-ChildItem -Path "$env:USERPROFILE\.m2\repository\com\example\osb-service\1.0.0\" -Filter "*.jar" | Select-Object -ExpandProperty FullName
          if (-not $jarFile) { 
            Write-Host "Error: JAR file not found!" 
            exit 1 
          }
          Write-Host "Found JAR: $jarFile"
          Copy-Item -Path $jarFile -Destination "C:\Oracle\Middleware\deployments\osb\" -Force
          echo "JAR_FILE=C:\Oracle\Middleware\deployments\osb\osb-service-1.0.0.jar" >> $env:GITHUB_ENV

      - name: Deploy OSB Using WLST
        shell: cmd
        run: |
          C:\Oracle\Middleware\OMW_Home\oracle_common\common\bin\wlst.cmd C:\Oracle\Middleware\deployments\osb\deploy_osb.py "%JAR_FILE%"
