name: Build and Publish OSB Project

on:
  push:
    branches:
      - main  # Change to your main branch name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.9

      - name: Build OSB Project
        run: mvn clean package

      - name: Publish Artifact to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
